version: '3'
services:
  internal_server:
    build:
      dockerfile: module_gateway/internal_server/Dockerfile
    network_mode: host
    ports:
      - 8888:8888
    depends_on:
      - ipc-mosquitto
    environment:
      - IPC_MQTT_HOST=localhost

  module_handler:
    build:
      dockerfile: module_gateway/module_handler/Dockerfile
    network_mode: host
    depends_on:
      - ipc-mosquitto
    environment:
      - IPC_MQTT_HOST=localhost

  external_client:
    build:
      dockerfile: module_gateway/external_client/Dockerfile
    network_mode: host
    depends_on:
      - ipc-mosquitto
    environment:
      - IPC_MQTT_HOST=localhost

  period_checker:
    build:
      dockerfile: module_gateway/period_checker/Dockerfile
    network_mode: host
    depends_on:
      - ipc-mosquitto
    environment:
      - IPC_MQTT_HOST=localhost

  ipc-mosquitto:
    image: eclipse-mosquitto
    network_mode: host
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:z
    ports:
      - 1883:1883

networks: {}